name: Publish Docs

on:
  workflow_dispatch:

jobs:
  deploy-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install poetry using pip
        run: pipx install poetry==1.7.0

      - name: Get current version
        id: version
        run: echo "version=$(node -p "require('./packages/jspsych/package.json').version")" >> "$GITHUB_ENV"

      - name: Remove patch version
        run: echo "version_major_minor=${{ env.version }}" | awk -F. '{print $1"."$2}' >> "$GITHUB_ENV"

      - name: Deploy docs
        run: npm run docs:deploy ${{ env.version_major_minor }}

      - name: Checkout gh-docs branch
        uses: actions/checkout@v2
        with:
          ref: gh-docs

      - name: Push gh-docs branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-docs
          force: true


